import inspect
from dataclasses import dataclass
from types import NoneType
from typing import Any, Callable, Type, Union, get_args, get_origin

import httpx
import pytest

from gitcode_api._models import (
    APIObject,
    Blob,
    Branch,
    BranchDetail,
    Commit,
    CommitComment,
    CommitComparison,
    CommitResult,
    CommitSummary,
    ContentObject,
    Contributor,
    Email,
    EnterpriseMember,
    Issue,
    Label,
    MergeResult,
    Milestone,
    Namespace,
    OAuthToken,
    Organization,
    OrganizationMembership,
    OrganizationSummary,
    ProtectedBranch,
    ProtectedTag,
    PullRequest,
    PullRequestComment,
    PullRequestCount,
    PullRequestFile,
    Release,
    RepoCollaborator,
    RepoMember,
    RepoMemberPermission,
    Repository,
    SearchIssue,
    SearchRepository,
    SearchUser,
    Tag,
    Tree,
    User,
    UserSummary,
    Webhook,
)
from tests.restful_docs_examples._doc_helpers import (
    assert_payload_matches_object,
    get_value,
    load_response_payload,
    make_json_handler,
)


@dataclass
class DocsResponseCase:
    id: str
    doc_relative_path: str
    section_title: str
    method: str
    expected_path: str
    invoke: Callable[[Any], Any]
    model_type: Type[Any]
    value_path: str
    is_list: bool = False
    payload_normalizer: Callable[[Any], Any] | None = None


def _get_case_method(client: Any, case: DocsResponseCase) -> Callable[..., Any]:
    resource_name, method_name = case.invoke.__code__.co_names[:2]
    return getattr(getattr(client, resource_name), method_name)


def _annotation_matches_case(annotation: Any, case: DocsResponseCase) -> bool:
    origin = get_origin(annotation)

    if origin in (list, list.__class__):  # pragma: no cover - defensive
        args = get_args(annotation)
        return case.is_list and bool(args) and args[0] is case.model_type

    if origin is list:
        args = get_args(annotation)
        return case.is_list and bool(args) and args[0] is case.model_type

    if origin in (Union, getattr(__import__("types"), "UnionType", Union)):
        return any(_annotation_matches_case(option, case) for option in get_args(annotation) if option is not NoneType)

    return not case.is_list and annotation is case.model_type


def test_doc_cases_match_resource_return_annotations(sync_client_factory) -> None:
    client, http_client = sync_client_factory(lambda request: httpx.Response(200, json={}, request=request))

    try:
        for case in CASES:
            method = _get_case_method(client, case)
            annotation = inspect.signature(method).return_annotation
            assert annotation is not inspect.Signature.empty, f"Missing return annotation for {case.id}"
            assert _annotation_matches_case(annotation, case), (
                f"{case.id} expects {'list[' if case.is_list else ''}{case.model_type.__name__}"
                f"{']' if case.is_list else ''}, but {method.__qualname__} is annotated as {annotation!r}"
            )
    finally:
        client.close()
        http_client.close()


CASES = [
    DocsResponseCase(
        id="users-get-user",
        doc_relative_path="users.rst",
        section_title="1. Get a user",
        method="GET",
        expected_path="/api/v5/users/demo-user",
        invoke=lambda client: client.users.get(username="demo-user"),
        model_type=User,
        value_path="login",
    ),
    DocsResponseCase(
        id="users-list-emails",
        doc_relative_path="users.rst",
        section_title="3. Get all emails of the authorized user",
        method="GET",
        expected_path="/api/v5/emails",
        invoke=lambda client: client.users.list_emails(),
        model_type=Email,
        value_path="email",
        is_list=True,
    ),
    DocsResponseCase(
        id="users-me",
        doc_relative_path="users.rst",
        section_title="2. Get the profile of the authorized user",
        method="GET",
        expected_path="/api/v5/user",
        invoke=lambda client: client.users.me(),
        model_type=User,
        value_path="login",
    ),
    DocsResponseCase(
        id="users-list-events",
        doc_relative_path="users.rst",
        section_title="4. Get the personal activity of a user",
        method="GET",
        expected_path="/api/v5/users/demo-user/events",
        invoke=lambda client: client.users.list_events(username="demo-user"),
        model_type=APIObject,
        value_path="next",
    ),
    DocsResponseCase(
        id="users-list-repos",
        doc_relative_path="users.rst",
        section_title="5. Get the public repositories of a user",
        method="GET",
        expected_path="/api/v5/users/demo-user/repos",
        invoke=lambda client: client.users.list_repos(username="demo-user"),
        model_type=Repository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-create-personal",
        doc_relative_path="users.rst",
        section_title="6. Create a personal project repository",
        method="POST",
        expected_path="/api/v5/user/repos",
        invoke=lambda client: client.repos.create_personal(name="demo-repo"),
        model_type=Repository,
        value_path="full_name",
    ),
    DocsResponseCase(
        id="repos-list-user",
        doc_relative_path="users.rst",
        section_title="7. List all repositories of the authorized user",
        method="GET",
        expected_path="/api/v5/user/repos",
        invoke=lambda client: client.repos.list_user(),
        model_type=Repository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="users-create-key",
        doc_relative_path="users.rst",
        section_title="9. Add a public key",
        method="POST",
        expected_path="/api/v5/user/keys",
        invoke=lambda client: client.users.create_key(key="ssh-rsa AAA", title="demo-key"),
        model_type=APIObject,
        value_path="id",
    ),
    DocsResponseCase(
        id="users-list-keys",
        doc_relative_path="users.rst",
        section_title="10. List all public keys of the authorized user",
        method="GET",
        expected_path="/api/v5/user/keys",
        invoke=lambda client: client.users.list_keys(),
        model_type=APIObject,
        value_path="id",
        is_list=True,
    ),
    DocsResponseCase(
        id="users-get-key",
        doc_relative_path="users.rst",
        section_title="12. Get a specific public key",
        method="GET",
        expected_path="/api/v5/user/keys/1",
        invoke=lambda client: client.users.get_key(key_id=1),
        model_type=APIObject,
        value_path="id",
        payload_normalizer=lambda payload: payload[0],
    ),
    DocsResponseCase(
        id="users-get-namespace",
        doc_relative_path="users.rst",
        section_title="13. Obtain a namespace for authorized users",
        method="GET",
        expected_path="/api/v5/user/namespace",
        invoke=lambda client: client.users.get_namespace(path="demo-org"),
        model_type=Namespace,
        value_path="path",
    ),
    DocsResponseCase(
        id="users-list-starred",
        doc_relative_path="users.rst",
        section_title="14. List the repository where authorized user star has been listed",
        method="GET",
        expected_path="/api/v5/user/starred",
        invoke=lambda client: client.users.list_starred(),
        model_type=Repository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-list-for-user",
        doc_relative_path="orgs.rst",
        section_title="1. List the organizations a user belongs to",
        method="GET",
        expected_path="/api/v5/users/demo-user/orgs",
        invoke=lambda client: client.orgs.list_for_user(username="demo-user"),
        model_type=OrganizationSummary,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-list-authenticated",
        doc_relative_path="orgs.rst",
        section_title="2. List the organizations an authorized user belongs to",
        method="GET",
        expected_path="/api/v5/users/orgs",
        invoke=lambda client: client.orgs.list_authenticated(),
        model_type=OrganizationSummary,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-get-member",
        doc_relative_path="orgs.rst",
        section_title="3. Get details of an organization member",
        method="GET",
        expected_path="/api/v5/orgs/demo-org/members/demo-user",
        invoke=lambda client: client.orgs.get_member(org="demo-org", username="demo-user"),
        model_type=OrganizationMembership,
        value_path="user.login",
    ),
    DocsResponseCase(
        id="orgs-get-organization",
        doc_relative_path="orgs.rst",
        section_title="4. Get information about an organization",
        method="GET",
        expected_path="/api/v5/orgs/demo-org",
        invoke=lambda client: client.orgs.get(org="demo-org"),
        model_type=Organization,
        value_path="login",
    ),
    DocsResponseCase(
        id="orgs-list-repos",
        doc_relative_path="orgs.rst",
        section_title="5. Get the repo list of an organization",
        method="GET",
        expected_path="/api/v5/orgs/demo-org/repos",
        invoke=lambda client: client.orgs.list_repos(org="demo-org"),
        model_type=Repository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-create-repo",
        doc_relative_path="orgs.rst",
        section_title="6. Create a repository for an organization",
        method="POST",
        expected_path="/api/v5/orgs/demo-org/repos",
        invoke=lambda client: client.orgs.create_repo(org="demo-org", name="demo-repo"),
        model_type=Repository,
        value_path="full_name",
    ),
    DocsResponseCase(
        id="orgs-get-enterprise-member",
        doc_relative_path="orgs.rst",
        section_title="7. Get a specific member of a enterprise",
        method="GET",
        expected_path="/api/v5/enterprises/demo-enterprise/members/demo-user",
        invoke=lambda client: client.orgs.get_enterprise_member(enterprise="demo-enterprise", username="demo-user"),
        model_type=EnterpriseMember,
        value_path="user.login",
    ),
    DocsResponseCase(
        id="orgs-get-membership",
        doc_relative_path="orgs.rst",
        section_title="8. Get the member profile of an authorized user in an organization",
        method="GET",
        expected_path="/api/v5/user/memberships/orgs/demo-org",
        invoke=lambda client: client.orgs.get_membership(org="demo-org"),
        model_type=OrganizationMembership,
        value_path="organization.login",
    ),
    DocsResponseCase(
        id="orgs-list-enterprise-members",
        doc_relative_path="orgs.rst",
        section_title="10. List all members of a enterprise",
        method="GET",
        expected_path="/api/v5/enterprises/demo-enterprise/members",
        invoke=lambda client: client.orgs.list_enterprise_members(enterprise="demo-enterprise"),
        model_type=EnterpriseMember,
        value_path="user.login",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-list-followers",
        doc_relative_path="orgs.rst",
        section_title="12. List all followers of a specific organization",
        method="GET",
        expected_path="/api/v5/orgs/demo-org/followers",
        invoke=lambda client: client.orgs.list_followers(owner="demo-org"),
        model_type=User,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-get-issue-extend-settings",
        doc_relative_path="orgs.rst",
        section_title="13. Get extended issue configuration",
        method="GET",
        expected_path="/api/v5/orgs/demo-org/issue/extend/settings",
        invoke=lambda client: client.orgs.get_issue_extend_settings(org="demo-org"),
        model_type=APIObject,
        value_path="type_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="orgs-invite-member",
        doc_relative_path="orgs.rst",
        section_title="14. Invite an Organization Member",
        method="POST",
        expected_path="/api/v5/orgs/demo-org/memberships/demo-user",
        invoke=lambda client: client.orgs.invite_member(org="demo-org", username="demo-user"),
        model_type=User,
        value_path="login",
    ),
    DocsResponseCase(
        id="orgs-update-enterprise-member",
        doc_relative_path="orgs.rst",
        section_title="15. Modify Enterprise Member Permissions",
        method="PUT",
        expected_path="/api/v5/enterprises/demo-enterprise/members/demo-user",
        invoke=lambda client: client.orgs.update_enterprise_member(
            enterprise="demo-enterprise", username="demo-user", role="viewer"
        ),
        model_type=EnterpriseMember,
        value_path="user.login",
    ),
    DocsResponseCase(
        id="orgs-update",
        doc_relative_path="orgs.rst",
        section_title="16. Update the organizational information managed by authorized users",
        method="PATCH",
        expected_path="/api/v5/orgs/demo-org",
        invoke=lambda client: client.orgs.update(org="demo-org", name="demo-org"),
        model_type=Organization,
        value_path="path",
    ),
    DocsResponseCase(
        id="search-users",
        doc_relative_path="search.rst",
        section_title="1. Search Users",
        method="GET",
        expected_path="/api/v5/search/users",
        invoke=lambda client: client.search.users(q="demo"),
        model_type=SearchUser,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="search-issues",
        doc_relative_path="search.rst",
        section_title="2. Search Issues",
        method="GET",
        expected_path="/api/v5/search/issues",
        invoke=lambda client: client.search.issues(q="demo"),
        model_type=SearchIssue,
        value_path="repository.full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="search-repositories",
        doc_relative_path="search.rst",
        section_title="3. Search Repositories",
        method="GET",
        expected_path="/api/v5/search/repositories",
        invoke=lambda client: client.search.repositories(q="demo"),
        model_type=SearchRepository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-get-tree",
        doc_relative_path="repos.rst",
        section_title="1. Get a tree",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/git/trees/main",
        invoke=lambda client: client.contents.get_tree(sha="main"),
        model_type=Tree,
        value_path="tree.0.path",
    ),
    DocsResponseCase(
        id="repos-get-blob",
        doc_relative_path="repos.rst",
        section_title="7. Get File Blob",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/git/blobs/blob-sha",
        invoke=lambda client: client.contents.get_blob(sha="blob-sha"),
        model_type=Blob,
        value_path="sha",
    ),
    DocsResponseCase(
        id="repos-get-content",
        doc_relative_path="repos.rst",
        section_title="2. Retrieve Contents Under a Specific Repository Path",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/contents/README.md",
        invoke=lambda client: client.contents.get(path="README.md"),
        model_type=ContentObject,
        value_path="path",
    ),
    DocsResponseCase(
        id="repos-update-file",
        doc_relative_path="repos.rst",
        section_title="5. Update File",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/contents/README.md",
        invoke=lambda client: client.contents.update(
            path="README.md",
            content="ZGVtbw==",
            message="update file",
            sha="demo-sha",
        ),
        model_type=CommitResult,
        value_path="content.path",
    ),
    DocsResponseCase(
        id="repos-list-contributors",
        doc_relative_path="repos.rst",
        section_title="9. Get Repository Contributors",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/contributors",
        invoke=lambda client: client.repos.list_contributors(),
        model_type=Contributor,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-update-module-settings",
        doc_relative_path="repos.rst",
        section_title="10. Set Repository Modules",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/module/setting",
        invoke=lambda client: client.repos.update_module_settings(issue=True),
        model_type=APIObject,
        value_path="msg",
    ),
    DocsResponseCase(
        id="repos-update-reviewer-settings",
        doc_relative_path="repos.rst",
        section_title="12. Modify Repository Code Review Settings",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/reviewer",
        invoke=lambda client: client.repos.update_reviewer_settings(enable=True),
        model_type=APIObject,
        value_path="id",
    ),
    DocsResponseCase(
        id="repos-fork",
        doc_relative_path="repos.rst",
        section_title="21. Fork a Repository",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/forks",
        invoke=lambda client: client.repos.fork(),
        model_type=Repository,
        value_path="full_name",
    ),
    DocsResponseCase(
        id="repos-list-forks",
        doc_relative_path="repos.rst",
        section_title="22. List Forks of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/forks",
        invoke=lambda client: client.repos.list_forks(),
        model_type=Repository,
        value_path="full_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-list-subscribers",
        doc_relative_path="repos.rst",
        section_title="25. List Users Watching a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/subscribers",
        invoke=lambda client: client.repos.list_subscribers(),
        model_type=UserSummary,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-update-repo-settings",
        doc_relative_path="repos.rst",
        section_title="27. Update Repository Settings",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/repo_settings",
        invoke=lambda client: client.repos.update_repo_settings(enable=True),
        model_type=APIObject,
        value_path="disable_fork",
    ),
    DocsResponseCase(
        id="repos-get-repo-settings",
        doc_relative_path="repos.rst",
        section_title="28. Get Repository Settings",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/repo_settings",
        invoke=lambda client: client.repos.get_repo_settings(),
        model_type=APIObject,
        value_path="disable_fork",
    ),
    DocsResponseCase(
        id="repos-get-pull-request-settings",
        doc_relative_path="repos.rst",
        section_title="29. Get Pull Request Settings",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pull_request_settings",
        invoke=lambda client: client.repos.get_pull_request_settings(),
        model_type=APIObject,
        value_path="merge_method",
    ),
    DocsResponseCase(
        id="repos-update-pull-request-settings",
        doc_relative_path="repos.rst",
        section_title="30. Update Pull Request Settings",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pull_request_settings",
        invoke=lambda client: client.repos.update_pull_request_settings(enable=True),
        model_type=APIObject,
        value_path="merge_method",
    ),
    DocsResponseCase(
        id="repos-list-customized-roles",
        doc_relative_path="repos.rst",
        section_title="34. Get Custom Roles of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/customized_roles",
        invoke=lambda client: client.repos.list_customized_roles(),
        model_type=APIObject,
        value_path="role_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="repos-get-download-statistics",
        doc_relative_path="repos.rst",
        section_title="35. Download Statistics",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/download_statistics",
        invoke=lambda client: client.repos.get_download_statistics(),
        model_type=APIObject,
        value_path="download_statistics_total",
    ),
    DocsResponseCase(
        id="repos-list-stargazers",
        doc_relative_path="repos.rst",
        section_title="26. List Users Starring a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/stargazers",
        invoke=lambda client: client.repos.list_stargazers(),
        model_type=UserSummary,
        value_path="login",
        is_list=True,
    ),
    DocsResponseCase(
        id="branch-list",
        doc_relative_path="repos/branch.rst",
        section_title="1. Get All Branches of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/branches",
        invoke=lambda client: client.branches.list(),
        model_type=Branch,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="branch-create",
        doc_relative_path="repos/branch.rst",
        section_title="2. Create a Branch",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/branches",
        invoke=lambda client: client.branches.create(branch="demo-branch", ref="main"),
        model_type=Branch,
        value_path="name",
    ),
    DocsResponseCase(
        id="branch-get-branch",
        doc_relative_path="repos/branch.rst",
        section_title="3. Get a Branch",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/branches/main",
        invoke=lambda client: client.branches.get(branch="main"),
        model_type=BranchDetail,
        value_path="commit.id",
    ),
    DocsResponseCase(
        id="branch-list-protected",
        doc_relative_path="repos/branch.rst",
        section_title="6. Get List of Protected Branch Rules",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/protect_branches",
        invoke=lambda client: client.branches.list_protected(),
        model_type=ProtectedBranch,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="commit-list",
        doc_relative_path="repos/commit.rst",
        section_title="1. Get All Commits of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/commits",
        invoke=lambda client: client.commits.list(),
        model_type=CommitSummary,
        value_path="sha",
        is_list=True,
    ),
    DocsResponseCase(
        id="commit-get-commit",
        doc_relative_path="repos/commit.rst",
        section_title="2. Get a Specific Commit of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/commits/main",
        invoke=lambda client: client.commits.get(sha="main"),
        model_type=Commit,
        value_path="files.0.filename",
    ),
    DocsResponseCase(
        id="commit-compare",
        doc_relative_path="repos/commit.rst",
        section_title="3. Compare Commits",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/compare/base...head",
        invoke=lambda client: client.commits.compare(base="base", head="head"),
        model_type=CommitComparison,
        value_path="base_commit.sha",
    ),
    DocsResponseCase(
        id="commit-create-comment",
        doc_relative_path="repos/commit.rst",
        section_title="4. Create a Commit Comment",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/commits/demo-sha/comments",
        invoke=lambda client: client.commits.create_comment(sha="demo-sha", body="demo comment"),
        model_type=CommitComment,
        value_path="body",
    ),
    DocsResponseCase(
        id="commit-get-comment",
        doc_relative_path="repos/commit.rst",
        section_title="7. Get a Specific Commit Comment of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/comments/1",
        invoke=lambda client: client.commits.get_comment(comment_id=1),
        model_type=CommitComment,
        value_path="id",
    ),
    DocsResponseCase(
        id="commit-update-comment",
        doc_relative_path="repos/commit.rst",
        section_title="8. Update a Commit Comment",
        method="PATCH",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/comments/1",
        invoke=lambda client: client.commits.update_comment(comment_id=1, body="updated comment"),
        model_type=CommitComment,
        value_path="body",
    ),
    DocsResponseCase(
        id="issues-create-issue",
        doc_relative_path="repos/issues.rst",
        section_title="1. Create an Issue",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/issues",
        invoke=lambda client: client.issues.create(owner="SushiNinja", title="demo issue"),
        model_type=Issue,
        value_path="title",
    ),
    DocsResponseCase(
        id="pulls-list",
        doc_relative_path="repos/pulls.rst",
        section_title="1. Get the List of Pull Requests",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls",
        invoke=lambda client: client.pulls.list(only_count=True),
        model_type=PullRequestCount,
        value_path="all",
    ),
    DocsResponseCase(
        id="pulls-merge",
        doc_relative_path="repos/pulls.rst",
        section_title="2. Merge a Pull Request",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/merge",
        invoke=lambda client: client.pulls.merge(number=1),
        model_type=MergeResult,
        value_path="merged",
    ),
    DocsResponseCase(
        id="pulls-list-issues",
        doc_relative_path="repos/pulls.rst",
        section_title="3. Get Issues Associated with a Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/issues",
        invoke=lambda client: client.pulls.list_issues(number=1),
        model_type=Issue,
        value_path="title",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-create-comment",
        doc_relative_path="repos/pulls.rst",
        section_title="4. Submit a Pull Request Comment",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/comments",
        invoke=lambda client: client.pulls.create_comment(number=1, body="demo comment"),
        model_type=PullRequestComment,
        value_path="body",
    ),
    DocsResponseCase(
        id="pulls-list-files",
        doc_relative_path="repos/pulls.rst",
        section_title="5. List Files in a Pull Request Commit",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/files",
        invoke=lambda client: client.pulls.list_files(number=1),
        model_type=PullRequestFile,
        value_path="filename",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-list-comments",
        doc_relative_path="repos/pulls.rst",
        section_title="6. Get All Comments for a Specific Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/comments",
        invoke=lambda client: client.pulls.list_comments(number=1),
        model_type=PullRequestComment,
        value_path="body",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-get-pull-request",
        doc_relative_path="repos/pulls.rst",
        section_title="9. Get a Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1",
        invoke=lambda client: client.pulls.get(number=1),
        model_type=PullRequest,
        value_path="head.ref",
    ),
    DocsResponseCase(
        id="pulls-create-labels",
        doc_relative_path="repos/pulls.rst",
        section_title="11. Create a Pull Request Label",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/labels",
        invoke=lambda client: client.pulls.add_labels(number=1, labels=["bug"]),
        model_type=Label,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-list-operation-logs",
        doc_relative_path="repos/pulls.rst",
        section_title="15. Get the events Log of a Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/operate_logs",
        invoke=lambda client: client.pulls.list_operation_logs(number=1),
        model_type=APIObject,
        value_path="action",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-list-labels",
        doc_relative_path="repos/pulls.rst",
        section_title="16. Get All Labels of a Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/1/labels",
        invoke=lambda client: client.pulls.list_labels(number=1),
        model_type=Label,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-get-comment",
        doc_relative_path="repos/pulls.rst",
        section_title="22. Get a Comment of Pull Request",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/pulls/comments/1",
        invoke=lambda client: client.pulls.get_comment(comment_id=1),
        model_type=PullRequestComment,
        value_path="id",
    ),
    DocsResponseCase(
        id="pulls-list-org",
        doc_relative_path="repos/pulls.rst",
        section_title="30. Get the List of Organization Pull Requests",
        method="GET",
        expected_path="/api/v5/org/demo-org/pull_requests",
        invoke=lambda client: client.pulls.list_org(org="demo-org"),
        model_type=PullRequest,
        value_path="number",
        is_list=True,
    ),
    DocsResponseCase(
        id="pulls-list-issue-pull-requests",
        doc_relative_path="repos/pulls.rst",
        section_title="31. Get Pull Requests Associated with an Enterprise Issue",
        method="GET",
        expected_path="/api/v5/enterprises/demo-enterprise/issues/1/pull_requests",
        invoke=lambda client: client.pulls.list_issue_pull_requests(enterprise="demo-enterprise", number=1),
        model_type=PullRequest,
        value_path="title",
        is_list=True,
    ),
    DocsResponseCase(
        id="labels-create-label",
        doc_relative_path="repos/labels.rst",
        section_title="3. Create a Label for a Repository",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/labels",
        invoke=lambda client: client.labels.create(name="demo", color="#123456"),
        model_type=Label,
        value_path="name",
    ),
    DocsResponseCase(
        id="milestones-create-milestone",
        doc_relative_path="repos/milestone.rst",
        section_title="5. Create a Milestone for a Repository",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/milestones",
        invoke=lambda client: client.milestones.create(title="demo", due_on="2026-01-01T00:00:00Z"),
        model_type=Milestone,
        value_path="title",
    ),
    DocsResponseCase(
        id="members-add-or-update",
        doc_relative_path="repos/member.rst",
        section_title="1. Add or Update Repository Member Permissions",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/collaborators/demo-user",
        invoke=lambda client: client.members.add_or_update(username="demo-user", permission="push"),
        model_type=RepoMember,
        value_path="login",
    ),
    DocsResponseCase(
        id="members-list",
        doc_relative_path="repos/member.rst",
        section_title="3. Get All Members of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/collaborators",
        invoke=lambda client: client.members.list(),
        model_type=RepoCollaborator,
        value_path="username",
        is_list=True,
    ),
    DocsResponseCase(
        id="members-get",
        doc_relative_path="repos/member.rst",
        section_title="4. Check if a User is a Member of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/collaborators/demo-user",
        invoke=lambda client: client.members.get(username="demo-user"),
        model_type=APIObject,
        value_path="message",
    ),
    DocsResponseCase(
        id="members-get-permission",
        doc_relative_path="repos/member.rst",
        section_title="5. View the Permissions of a Repository Member",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/collaborators/demo-user/permission",
        invoke=lambda client: client.members.get_permission(username="demo-user"),
        model_type=RepoMemberPermission,
        value_path="permission",
    ),
    DocsResponseCase(
        id="releases-update",
        doc_relative_path="repos/release.rst",
        section_title="1. Update Repository Release",
        method="PATCH",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/releases/1",
        invoke=lambda client: client.releases.update(release_id=1, tag_name="v1.0.0", name="v1.0.0", body="demo"),
        model_type=Release,
        value_path="tag_name",
    ),
    DocsResponseCase(
        id="releases-get-by-tag",
        doc_relative_path="repos/release.rst",
        section_title="2. Get Repository Release by Tag Name",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/releases/tags/v1.0.0",
        invoke=lambda client: client.releases.get_by_tag(tag="v1.0.0"),
        model_type=Release,
        value_path="tag_name",
    ),
    DocsResponseCase(
        id="releases-list",
        doc_relative_path="repos/release.rst",
        section_title="3. Get All Releases of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/releases",
        invoke=lambda client: client.releases.list(),
        model_type=Release,
        value_path="tag_name",
        is_list=True,
    ),
    DocsResponseCase(
        id="tags-list",
        doc_relative_path="repos/tag.rst",
        section_title="1. List All Tags of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/tags",
        invoke=lambda client: client.tags.list(),
        model_type=Tag,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="tags-create",
        doc_relative_path="repos/tag.rst",
        section_title="2. Create a Tag for a Repository",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/tags",
        invoke=lambda client: client.tags.create(refs="main", tag_name="v1.0.0"),
        model_type=Tag,
        value_path="commit.sha",
    ),
    DocsResponseCase(
        id="tags-list-protected",
        doc_relative_path="repos/tag.rst",
        section_title="3. List Protected Tags for a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/protected_tags",
        invoke=lambda client: client.tags.list_protected(),
        model_type=ProtectedTag,
        value_path="name",
        is_list=True,
    ),
    DocsResponseCase(
        id="tags-get-protected",
        doc_relative_path="repos/tag.rst",
        section_title="5. Get Protected Tag Details",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/protected_tags/v1.0.0",
        invoke=lambda client: client.tags.get_protected(tag_name="v1.0.0"),
        model_type=ProtectedTag,
        value_path="name",
    ),
    DocsResponseCase(
        id="tags-create-protected",
        doc_relative_path="repos/tag.rst",
        section_title="6. Create Protected Tag",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/protected_tags",
        invoke=lambda client: client.tags.create_protected(name="v1.0.0"),
        model_type=ProtectedTag,
        value_path="name",
    ),
    DocsResponseCase(
        id="tags-update-protected",
        doc_relative_path="repos/tag.rst",
        section_title="7. Update Protected Tag",
        method="PUT",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/protected_tags",
        invoke=lambda client: client.tags.update_protected(name="v1.0.0", create_access_level=30),
        model_type=ProtectedTag,
        value_path="name",
    ),
    DocsResponseCase(
        id="webhooks-list",
        doc_relative_path="repos/webhooks.rst",
        section_title="1. List WebHooks of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/hooks",
        invoke=lambda client: client.webhooks.list(),
        model_type=Webhook,
        value_path="url",
        is_list=True,
    ),
    DocsResponseCase(
        id="webhooks-create",
        doc_relative_path="repos/webhooks.rst",
        section_title="2. Create a WebHook for a Repository",
        method="POST",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/hooks",
        invoke=lambda client: client.webhooks.create(url="https://example.com/hook"),
        model_type=Webhook,
        value_path="url",
    ),
    DocsResponseCase(
        id="webhooks-get",
        doc_relative_path="repos/webhooks.rst",
        section_title="3. Get a Specific WebHook of a Repository",
        method="GET",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/hooks/1",
        invoke=lambda client: client.webhooks.get(hook_id=1),
        model_type=Webhook,
        value_path="url",
    ),
    DocsResponseCase(
        id="webhooks-update",
        doc_relative_path="repos/webhooks.rst",
        section_title="4. Update a WebHook of a Repository",
        method="PATCH",
        expected_path="/api/v5/repos/SushiNinja/GitCode-API/hooks/1",
        invoke=lambda client: client.webhooks.update(hook_id=1, url="https://example.com/hook"),
        model_type=Webhook,
        value_path="url",
    ),
]


@pytest.mark.parametrize("case", CASES, ids=[case.id for case in CASES])
def test_doc_response_examples_deserialize_to_expected_models(case: DocsResponseCase, sync_client_factory) -> None:
    payload = load_response_payload(case.doc_relative_path, case.section_title)
    if case.payload_normalizer is not None:
        payload = case.payload_normalizer(payload)
    client, http_client = sync_client_factory(
        make_json_handler(case.expected_path, payload, method=case.method),
        owner="SushiNinja",
        repo="GitCode-API",
    )

    try:
        result = case.invoke(client)
    finally:
        client.close()
        http_client.close()

    if case.is_list:
        assert isinstance(result, list)
        assert result
        assert len(result) == len(payload)
        assert isinstance(result[0], case.model_type)
        assert_payload_matches_object(payload, result)
        assert get_value(result[0], case.value_path) == get_value(payload[0], case.value_path)
        return

    assert isinstance(result, case.model_type)
    assert_payload_matches_object(payload, result)
    assert get_value(result, case.value_path) == get_value(payload, case.value_path)


def test_oauth_exchange_token_uses_documented_response_model(
    monkeypatch: pytest.MonkeyPatch,
    sync_client_factory,
) -> None:
    payload = load_response_payload("oauth.rst", "3. Obtaining an Authorization Token")

    def fake_post(url: str, **kwargs: Any) -> httpx.Response:
        assert url == "https://gitcode.com/oauth/token"
        assert kwargs["params"]["grant_type"] == "authorization_code"
        return httpx.Response(200, json=payload, request=httpx.Request("POST", url))

    from gitcode_api.resources import account as account_resources

    monkeypatch.setattr(account_resources.httpx, "post", fake_post)

    client, http_client = sync_client_factory(lambda request: httpx.Response(200, json={}, request=request))
    try:
        token = client.oauth.exchange_token(code="demo-code", client_id="demo-client", client_secret="demo-secret")
    finally:
        client.close()
        http_client.close()

    assert isinstance(token, OAuthToken)
    assert_payload_matches_object(payload, token)
    assert token.access_token == get_value(payload, "access_token")
